version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/MyCinderProject
    ports:
      - "8080:8080"
    command: ./build/MyCinderProject

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mycinderproject
    ports:
      - "5432:5432"