name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up C++
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake build-essential

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Documentation to GitHub Pages
        run: |
          mkdocs gh-deploy --clean

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/MyCinderProject
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}